-- Use most plugins only on my local machine
local host = "emily"

---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  -- import/override with your plugins folder
  { import = "astrocommunity.pack.svelte", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.pack.gleam", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.pack.mdx", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.pack.tailwindcss", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.pack.astro", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.pack.go", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.pack.typescript-all-in-one", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.pack.docker", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.pack.rust", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.pack.html-css", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.pack.json", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.pack.yaml", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.lsp.nvim-lint", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.fuzzy-finder.fzf-lua", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.editing-support.conform-nvim", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.utility.mason-tool-installer-nvim" },
  -- { import = "astrocommunity.split-and-window.edgy-nvim" },
  -- { import = "astrocommunity.editing-support.yanky-nvim", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.colorscheme.everforest", enabled = true },
  { import = "astrocommunity.colorscheme.neofusion-nvim", enabled = true },
  { import = "astrocommunity.colorscheme.nightfox-nvim", enabled = true },
  { import = "astrocommunity.colorscheme.modus-nvim", enabled = true },
  { import = "astrocommunity.colorscheme.tokyonight-nvim", enabled = true },
  { import = "astrocommunity.icon.mini-icons", enabled = true },
  { import = "astrocommunity.neovim-lua-development.lazydev-nvim", enabled = true },
  -- { import = "astrocommunity.color.huez-nvim" },
  -- { import = "astrocommunity.completion.copilot-lua", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.completion.codeium-nvim", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.completion.codeium-vim" },
  -- { import = "astrocommunity.completion.copilot-cmp", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.markdown-and-latex.render-markdown-nvim", enable = (vim.fn.hostname() == host) },
  { import = "astrocommunity.media.img-clip-nvim", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.completion.avante-nvim", enable = (vim.fn.hostname() == host) },

  { import = "astrocommunity.media.vim-wakatime", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.git.fugit2-nvim", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.code-runner.sniprun", enable = (vim.fn.hostname() == host) },
  -- { import = "astrocommunity.pack.nix" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.recipes.astrolsp-no-insert-inlay-hints" },
  -- { import = "astrocommunity.lsp.lspsaga-nvim" },
  { import = "astrocommunity.pack.bash", enabled = false },
  -- { import = "astrocommunity.motion.flash-nvim" },
  { import = "astrocommunity.editing-support.todo-comments-nvim", enabled = true },
  { import = "astrocommunity.lsp.inc-rename-nvim", enabled = true },
  -- { import = "astrocommunity.note-taking.venn-nvim", enabled = true },
  -- { import = "astrocommunity.media.cord-nvim" },
  { import = "astrocommunity.motion.mini-move", enabled = true },
  { import = "astrocommunity.motion.mini-surround", enabled = true },
  { import = "astrocommunity.motion.vim-matchup", enabled = true },
  { import = "astrocommunity.motion.mini-bracketed", enabled = true },
  { import = "astrocommunity.bars-and-lines.vim-illuminate", enabled = true },
  { import = "astrocommunity.editing-support.mini-operators", enabled = true },
  -- { import = "astrocommunity.keybinding.nvcheatsheet-nvim", enabled = true },
  { import = "astrocommunity.motion.mini-ai" },
  -- { import = "astrocommunity.workflow.hardtime-nvim" },
  { import = "astrocommunity.editing-support.undotree" },
  -- { import = "astrocommunity.motion.grapple-nvim" },
  -- { import = "astrocommunity.editing-support.cloak-nvim" },
  -- { import = "astrocommunity.indent.mini-indentscope", enabled = true },
  -- { import = "astrocommunity.editing-support.rainbow-delimiters-nvim", enabled = true },
  { import = "astrocommunity.comment.ts-comments-nvim", enabled = true },
  -- { import = "astrocommunity.project.nvim-spectre", enabled = true },
  { import = "astrocommunity.diagnostics.trouble-nvim", enabled = true },
  { import = "astrocommunity.editing-support.dial-nvim", enabled = true },
  { import = "astrocommunity.utility.noice-nvim", enabled = true },
  { import = "astrocommunity.scrolling.mini-animate", enabled = true },
  { import = "astrocommunity.fuzzy-finder.telescope-zoxide", enabled = false },
  -- { import = "astrocommunity.git.neogit" },
  { import = "astrocommunity.motion.portal-nvim", enabled = true },
  { import = "astrocommunity.recipes.vscode", enabled = true },
  { import = "astrocommunity.editing-support.mini-splitjoin", enabled = true },
  -- { import = "astrocommunity.workflow.hardtime-nvim", enabled = true },
  { import = "astrocommunity.file-explorer.oil-nvim", enabled = true },
}
