---@type LazySpec
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  -- { import = "astrocommunity.pack.astro" },
  { import = "astrocommunity.pack.svelte" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.pack.mdx" },
  { import = "astrocommunity.pack.markdown" },
  { import = "astrocommunity.pack.typescript" },
  -- { import = "astrocommunity.pack.quarto" },
  { import = "astrocommunity.pack.python" },
  -- { import = "astrocommunity.pack.typst" },
  -- { import = "astrocommunity.pack.jj" },
  { import = "astrocommunity.lsp.nvim-lint" },
  { import = "astrocommunity.utility.mason-tool-installer-nvim" },
  -- { import = "astrocommunity.syntax.vim-sandwich" },
  { import = "astrocommunity.markdown-and-latex.markview-nvim" },
  { import = "astrocommunity.search.grug-far-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.editing-support.dial-nvim" },
  { import = "astrocommunity.motion.vim-matchup" },
  { import = "astrocommunity.motion.mini-move" },
  { import = "astrocommunity.motion.flash-nvim" },
  { import = "astrocommunity.motion.mini-surround" },
  { import = "astrocommunity.motion.mini-ai" },
  { import = "astrocommunity.motion.vim-matchup" },
  { import = "astrocommunity.motion.portal-nvim" },
  { import = "astrocommunity.comment.ts-comments-nvim" },
  { import = "astrocommunity.recipes.astrolsp-no-insert-inlay-hints" },
  -- { import = "astrocommunity.recipes.cache-colorscheme" },
  -- { import = "astrocommunity.recipes.neovide" },
  { import = "astrocommunity.recipes.vscode" },
  { import = "astrocommunity.lsp.inc-rename-nvim" },
  { import = "astrocommunity.terminal-integration.flatten-nvim" },
  { import = "astrocommunity.diagnostics.trouble-nvim" },
  { import = "astrocommunity.programming-language-support.kulala-nvim" },
  { import = "astrocommunity.completion.blink-cmp" },
  { import = "astrocommunity.note-taking.obsidian-nvim" },
  { import = "astrocommunity.git.neogit" },
  { import = "astrocommunity.editing-support.conform-nvim" },
  { import = "astrocommunity.editing-support.mcphub-nvim" },
  { import = "astrocommunity.editing-support.codecompanion-nvim" },
  -- { import = "astrocommunity.completion.copilot-vim-cmp" },
  --NOTE: disabled because manual installs
  -- { import = "astrocommunity.file-explorer.oil-nvim" },
  -- { import = "astrocommunity.utility.noice-nvim" },
  -- { import = "astrocommunity.completion.codeium-nvim" },
}
