function GUI()
  if vim.g.neovide then
    return false
  else
    return true
  end
end
return {
  { -- community plugins
    "luxus/astrocommunity",
  },
  { import = "astrocommunity.misc.pets-nvim", enabled = true },
  { import = "astrocommunity.pack.go", enabled = true },
  { import = "astrocommunity.lang.rust", enabled = true },
  { import = "astrocommunity.lang.python", enabled = false },
  { import = "astrocommunity.lang.nix", enabled = true },
  { import = "astrocommunity.lang.lua", enabled = true },
  { import = "astrocommunity.lang.typescript", enabled = false },
  { import = "astrocommunity.lang.clangd", enabled = false },
  { import = "astrocommunity.lang.json", enabled = false },
  { import = "astrocommunity.lang.sql", enabled = false },
  { import = "astrocommunity.lang.shell", enabled = true },
  { import = "astrocommunity.lang.tex", enabled = false },
  { import = "astrocommunity.colorschemes.catppuccin", enabled = true },
  { import = "astrocommunity.colorschemes.everforest", enabled = false },
  { import = "astrocommunity.colorschemes.nightfox", enabled = false },
  { import = "astrocommunity.colorschemes.onigiri", enabled = false },
  { import = "astrocommunity.colorschemes.kanagawa", enabled = false },
  { import = "astrocommunity.colorschemes.tokyonight", enabled = false },
  { import = "astrocommunity.ui.ministarter", enabled = true },
  { import = "astrocommunity.ui.ccc", enabled = false },
  { import = "astrocommunity.ui.drop", enabled = GUI() },
  { import = "astrocommunity.ui.minianimate", enabled = GUI() },
  { import = "astrocommunity.ui.noice", enabled = GUI() },
  { import = "astrocommunity.ui.glow", enabled = false },
  { import = "astrocommunity.ui.zen-mode", enabled = true },
  { import = "astrocommunity.ui.tint", enabled = true },
  { import = "astrocommunity.ui.scrollbar", enabled = true },
  { import = "astrocommunity.ui.smartcolumn", enabled = true },
  { import = "astrocommunity.ui.scope", enabled = true },
  { import = "astrocommunity.editor.minicomment", enabled = true },
  { import = "astrocommunity.editor.lsplines", enabled = false },
  { import = "astrocommunity.editor.grapple+portal", enabled = true },
  { import = "astrocommunity.editor.copilot", enabled = true },
  { import = "astrocommunity.editor.copilot-cmp", enabled = false },
  { import = "astrocommunity.editor.textobjects", enabled = false },
  { import = "astrocommunity.editor.miniai", enabled = true },
  { import = "astrocommunity.editor.minisurround", enabled = true },
  { import = "astrocommunity.editor.minimove", enabled = true },
  { import = "astrocommunity.editor.trouble", enabled = true },
  { import = "astrocommunity.editor.neoconf", enabled = true },
  { import = "astrocommunity.editor.cutlass", enabled = true },
  { import = "astrocommunity.editor.neogen", enabled = false },
  { import = "astrocommunity.editor.bqf", enabled = false },
  { import = "astrocommunity.tools.presence", enabled = true },
  { import = "astrocommunity.tools.chatgpt", enabled = true },
  { import = "astrocommunity.tools.wakatime", enabled = true },
  { import = "astrocommunity.tools.spectre", enabled = true },
  { import = "astrocommunity.tools.iron", enabled = false },
  { import = "astrocommunity.tools.neural", enabled = false },
  { import = "astrocommunity.tools.neorg", enabled = true },
  { import = "astrocommunity.tools.refactoring", enabled = false },
  { import = "astrocommunity.tools.octo", enabled = false },
  { import = "astrocommunity.tools.sg", enabled = true },
  { import = "astrocommunity.tools.fzf", enabled = false },
  { import = "astrocommunity.tools.oil", enabled = false },
  { import = "astrocommunity.tools.overseer", enabled = false },
  { import = "astrocommunity.tools.sniprun", enabled = false },
}
