return {
  require "user.plugins.extras.lang.go",
  require "user.plugins.extras.lang.rust",
  require "user.plugins.extras.lang.typescript",
  require "user.plugins.extras.ui.ministarter",
  require "user.plugins.extras.ui.ccc",
  require "user.plugins.extras.ui.drop",
  require "user.plugins.extras.ui.minianimate",
  require "user.plugins.extras.ui.noice",
  require "user.plugins.extras.editor.minicomment",
  require "user.plugins.extras.editor.grapple+portal",
  require "user.plugins.extras.editor.copilot",
  { "stevearc/oil.nvim", config = true, enabled = true, cmd = "Oil" },
  { "andweeb/presence.nvim", event = "VeryLazy" },
  { "wakatime/vim-wakatime", init = function() table.insert(astronvim.file_plugins, "vim-wakatime") end },
}
