return {
  require "user.plugins.extras.lang.go",
  require "user.plugins.extras.lang.rust",
  require "user.plugins.extras.lang.typescript",
  require "user.plugins.extras.ui.ministarter",
  require "user.plugins.extras.ui.ccc",
  require "user.plugins.extras.ui.drop",
  require "user.plugins.extras.ui.minianimate",
  require "user.plugins.extras.ui.noice",
  -- require "user.plugins.extras.ui.scrollbar",
  require "user.plugins.extras.editor.minicomment",
  require "user.plugins.extras.editor.grapple+portal",
  require "user.plugins.extras.editor.copilot",
  require "user.plugins.extras.editor.cutlass",
  require "user.plugins.extras.tools.oil",
  -- require "user.plugins.extras.tools.octo",
  -- require "user.plugins.extras.tools.sg",
  { "andweeb/presence.nvim", event = "VeryLazy" },
  -- { "mawkler/modicator.nvim", event = "VeryLazy", config = true }, --FIX: error about cursorline
  { "wakatime/vim-wakatime", init = function() table.insert(astronvim.file_plugins, "vim-wakatime") end },
}
